version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: portfolio-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./uploads:/app/uploads

  backend:
    build: .
    container_name: portfolio-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/portfolio
      DB_USER: portfolio
      DB_PASS: portfolio
      ADMIN_USER: diogo
      ADMIN_PASS: password
      JWT_SECRET: v9F!t2@wK7d#XqL8zP&jM4r$B1s^N6uY0eG*H3cQ+R5mZ%T2aV8oD9fL!xW7pJ
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: diogo.vieira.portfolioweb@gmail.com
      MAIL_PASSWORD: nzqbgukmcyjjqknd
      CLOUDINARY_CLOUD_NAME: dln5ztlpu
      CLOUDINARY_API_KEY: 395913657198274
      CLOUDINARY_API_SECRET: AE_kMnaijYZ59pUGbi8sXcuWIgk
    depends_on:
      - postgres

volumes:
  postgres_data:
